pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'repo_access', url: 'https://github.com/sultansaladd/devops-tools.git'
            }
        }

        stage('Execute Ansible Playbook') {
            steps {
                // Execute Ansible playbook with the selected environment
                // sh 'ansible-playbook python-playbook.yml -e "environment=${params.ENVIRONMENT}"'
                sh '''
                    ansible-playbook python-playbook.yml \
                    -e "environment=${params.ENVIRONMENT}" \
                    -e "ecr_image_url=${params.ECR_IMAGE_URL}"
                '''
            }
        }
    }
    
    // Parameters definition
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'uat', 'prod'], description: 'Select the environment')
    }
}
