pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'repo_access', url: 'https://github.com/sultansaladd/devops-tools.git'
            }
        }

        stage('Execute Ansible Playbook') {
            steps {
                // Execute Ansible playbook with the selected environment
                // sh 'ansible-playbook python-playbook.yml -e "environment=${params.ENVIRONMENT}"'
                sh '''
                    ansible --version
                    ansible-playbook --version
                    ansible-galaxy --version
                '''
            }
        }
    }
    
    // Parameters definition
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'uat', 'prod'], description: 'Select the environment')
    }
}
