pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'repo_access', url: 'https://github.com/sultansaladd/devops-tools.git'
            }
        }
        stage('Execute Ansible Playbook') {
            steps {
                // Execute Ansible playbook with the selected environment
                sh 'ansible-playbook playbook/nginx-playbook.yml -i inventory/dev.yaml'
            }
        }
    }
}